### ISSUE TITLE
esta logica debe estar en la entidad y no en el servicio

### ISSUE THREAD

**Issue by maurociancio** [jorgejcabrera/rent-app-service#11]
https://github.com/jorgejcabrera/rent-app-service/blob/7d49fcfab1cac7c7c61af61730fef9efcb6b074a/src/main/groovy/com/fiuba/rent_app/domain/order/service/OrderServiceAdapter.groovy#L21

**Comment by jorgejcabrera** [comment]
Done. Dejo el commit https://github.com/jorgejcabrera/rent-app-service/commit/08ed89e9d52c172bbe9f4138b2b4a669ffde29eb
