### ISSUE TITLE
capaz privado el metodo, no tiene mucho sentido que sea publico, o sí?

### ISSUE THREAD

**Issue by maurociancio** [jorgejcabrera/rent-app-service#15]
https://github.com/jorgejcabrera/rent-app-service/blob/08ed89e9d52c172bbe9f4138b2b4a669ffde29eb/src/main/groovy/com/fiuba/rent_app/domain/item/Item.groovy#L92

**Comment by jorgejcabrera** [comment]
si, tal cual. Lo hago privado 353a40491bb9eb46cb041b9b0a7dcd1a873e40a5
