### ISSUE TITLE
esta validacion deberia ir al dominio

### ISSUE THREAD

**Issue by maurociancio** [jorgejcabrera/rent-app-service#16]
https://github.com/jorgejcabrera/rent-app-service/blob/08ed89e9d52c172bbe9f4138b2b4a669ffde29eb/src/main/groovy/com/fiuba/rent_app/domain/item/service/ItemServiceImpl.groovy#L52

**Comment by jorgejcabrera** [comment]
Dale 177f0a54597ec18ee9765867d37629511a48c763
