### ISSUE TITLE
capaz todo se deberia resolver adentro del borrower?

### ISSUE THREAD

**Issue by maurociancio** [jorgejcabrera/rent-app-service#17]
https://github.com/jorgejcabrera/rent-app-service/blob/08ed89e9d52c172bbe9f4138b2b4a669ffde29eb/src/main/groovy/com/fiuba/rent_app/domain/order/service/OrderServiceAdapter.groovy#L27

        Order order = new Order(item, borrower)
        borrower.addOrder(order)

vs

borrwer.createOrder(item) y que haga todo? el new + el add?

**Comment by jorgejcabrera** [comment]
si, me agrada. Pero la acción, desde el punto de vista de un borrower sería alquilar (rent) 563db22a067d58485da417c7cbd663fa21563149
