### ISSUE TITLE
no valida ningun estado, creo que no se puede prestar dos veces la misma cosa no?

### ISSUE THREAD

**Issue by maurociancio** [jorgejcabrera/rent-app-service#3]
https://github.com/jorgejcabrera/rent-app-service/blob/cb8302b1891bcd4b23c6381ca89f201da98f504a/src/main/groovy/com/fiuba/rent_app/domain/item/Item.groovy#L77

**Comment by jorgejcabrera** [comment]
Hola Mauro, correcto. El servicio se encarga de realizar ese chequeo. https://github.com/jorgejcabrera/rent-app-service/blob/master/src/main/groovy/com/fiuba/rent_app/domain/order/service/OrderServiceAdapter.groovy#L21

**Comment by maurociancio** [comment]
Debe estar realizado en las clases del dominio.

**Comment by jorgejcabrera** [comment]
Hola Mauro, ahora el item sabe si puede ser rentado o no. Era esto lo que me mencionabas?

**Comment by maurociancio** [comment]
sip

**Comment by maurociancio** [comment]
void rent() {
        this.status = RENTED
    }


ese codigo sigue en la entidad. la entidad deberia validar que no pueda prestarse dos veces

**Comment by maurociancio** [comment]
no dije nada

**Comment by jorgejcabrera** [comment]
Cierro el issue, porque ahora el item sabe a traves de las ordenes si puede ser rentado o no: si existe una orden abierta, no se podra generar una nueva, es decir el item no podra ser rentado nuevamente hasta que no se devuelva.
