### ISSUE TITLE
puede ser parte de la clase item

### ISSUE THREAD

**Issue by maurociancio** [jorgejcabrera/rent-app-service#4]
class Item {
enum staus {...
}
}

https://github.com/jorgejcabrera/rent-app-service/blob/cb8302b1891bcd4b23c6381ca89f201da98f504a/src/main/groovy/com/fiuba/rent_app/domain/item/ItemStatus.groovy#L3

**Comment by jorgejcabrera** [comment]
Si me agrada. Con la salverdad de que ahora el status es de la orden. Muevo el enum a la orden
