### ISSUE TITLE
mejora?

### ISSUE THREAD

**Issue by maurociancio** [jorgejcabrera/rent-app-service#6]
orderCreationRules.forEach(rule -> rule.evaluate(order))

capaz si ese codigo está dentro del rent, te da la idea de las reglas de negocio a validar antes de rentear algo?

https://github.com/jorgejcabrera/rent-app-service/blob/cb8302b1891bcd4b23c6381ca89f201da98f504a/src/main/groovy/com/fiuba/rent_app/domain/order/service/OrderServiceAdapter.groovy#L25

**Comment by jorgejcabrera** [comment]
Hola Mauro, no habían visto esto antes. No existe una entidad rent como tal en mi modelo de dominio.  Un alquiler es representado por una orden. Vos te referís a mover estas reglas de validación hacía la Order?

**Comment by maurociancio** [comment]
claro, algo así decía.
