### ISSUE TITLE
podes usar nombres de metodos con espacios void "esto es un metodo"() {}

### ISSUE THREAD

**Issue by maurociancio** [jorgejcabrera/rent-app-service#8]
https://github.com/jorgejcabrera/rent-app-service/blob/ddadfd7c56b660e1e14153d27e7b528f4e45ce31/src/test/groovy/com/fiuba/rent_app/domain/item/ItemServiceTest.groovy#L40

**Comment by jorgejcabrera** [comment]
Buenísimo ahí lo pruebo
