### ISSUE TITLE
no valida estado antes de hacer la transicion

### ISSUE THREAD

**Issue by maurociancio** [jorgejcabrera/rent-app-service#9]
https://github.com/jorgejcabrera/rent-app-service/blob/ddadfd7c56b660e1e14153d27e7b528f4e45ce31/src/main/groovy/com/fiuba/rent_app/domain/order/Order.groovy#L74

**Comment by jorgejcabrera** [comment]
es, verdad voy a agregar la validacion

**Comment by jorgejcabrera** [comment]
Esto ya quedo solucionado. Antes de crear una nueva orden no pueden haber ordenes existentes abiertas.
